import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        earth: "hsl(var(--earth))",
        gold: "hsl(var(--gold))",
        "gold-light": "hsl(var(--gold-light))",
        green: "hsl(var(--green))",
        beige: "hsl(var(--beige))",
        cream: "hsl(var(--cream))",
        deep: "hsl(var(--deep))",
        copper: "hsl(var(--copper))",
        /* legacy names kept for compatibility */
        "earth-brown": "hsl(var(--earth))",
        "harvest-gold": "hsl(var(--gold))",
        "field-green": "hsl(var(--green))",
        "warm-beige": "hsl(var(--beige))",
        "deep-earth": "hsl(var(--deep))",
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        display: ['"Cormorant Garamond"', 'Georgia', 'serif'],
      },
      fontSize: {
        "display-lg": ["clamp(3rem, 8vw, 6rem)", { lineHeight: "0.92", letterSpacing: "-0.02em" }],
        "display-md": ["clamp(2.25rem, 5vw, 4rem)", { lineHeight: "0.96", letterSpacing: "-0.015em" }],
        "display-sm": ["clamp(1.75rem, 3.5vw, 2.75rem)", { lineHeight: "1.0", letterSpacing: "-0.01em" }],
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "var(--radius)",
        md: "calc(var(--radius) + 2px)",
        lg: "calc(var(--radius) + 4px)",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        gold: "var(--shadow-gold)",
        glow: "var(--shadow-glow)",
        warm: "var(--shadow-lg)",
        soft: "var(--shadow-md)",
        card: "var(--shadow-xl)",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
      transitionDuration: {
        "400": "400ms",
        "600": "600ms",
        "800": "800ms",
      },
      spacing: {
        "18": "4.5rem",
        "22": "5.5rem",
        "26": "6.5rem",
        "30": "7.5rem",
      },
      backgroundImage: {
        "gradient-hero": "linear-gradient(150deg, hsl(20,52%,11%) 0%, hsl(26,58%,18%) 50%, hsl(30,48%,15%) 100%)",
        "gradient-gold": "linear-gradient(135deg, hsl(42,90%,50%) 0%, hsl(36,82%,42%) 100%)",
        "gradient-warm": "linear-gradient(160deg, hsl(40,42%,95%) 0%, hsl(36,36%,90%) 100%)",
        "gradient-radial": "radial-gradient(ellipse at center, var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      animation: {
        "accordion-down": "accordion-down .25s ease-out",
        "accordion-up": "accordion-up .25s ease-out",
        "float": "floatY 4s ease-in-out infinite",
        "float-slow": "floatYSlow 6s ease-in-out infinite",
        "pulse-ring": "pulseRing 2s ease-out infinite",
        "spin-slow": "spin-slow 20s linear infinite",
        "gradient": "gradientMove 8s ease infinite",
        "slide-up": "slideUp .7s cubic-bezier(0.16,1,0.3,1) forwards",
        "slide-left": "slideLeft .7s cubic-bezier(0.16,1,0.3,1) forwards",
        "scale-in": "scaleIn .5s cubic-bezier(0.16,1,0.3,1) forwards",
        "fade-in": "fadeIn .6s ease forwards",
        "draw-line": "drawLine .6s cubic-bezier(0.16,1,0.3,1) forwards",
        "count-up": "countUp .8s cubic-bezier(0.16,1,0.3,1) forwards",
        "border-pulse": "borderPulse 2s ease-in-out infinite",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        floatY: { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-14px)" } },
        floatYSlow: { "0%,100%": { transform: "translateY(0) rotate(0deg)" }, "33%": { transform: "translateY(-8px) rotate(1deg)" }, "66%": { transform: "translateY(-14px) rotate(-1deg)" } },
        pulseRing: { "0%": { transform: "scale(1)", opacity: ".7" }, "100%": { transform: "scale(2.2)", opacity: "0" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        gradientMove: { "0%,100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        slideUp: { from: { opacity: "0", transform: "translateY(32px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideLeft: { from: { opacity: "0", transform: "translateX(-28px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        scaleIn: { from: { opacity: "0", transform: "scale(.92)" }, to: { opacity: "1", transform: "scale(1)" } },
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        drawLine: { from: { transform: "scaleX(0)", transformOrigin: "left" }, to: { transform: "scaleX(1)", transformOrigin: "left" } },
        countUp: { from: { opacity: "0", transform: "translateY(16px) scale(.9)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
        borderPulse: { "0%,100%": { borderColor: "hsl(42,90%,50%,.3)" }, "50%": { borderColor: "hsl(42,90%,50%,.8)" } },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
